### ISSUE TITLE
Errores del día 4

### ISSUE THREAD

**Issue by sgomez** [adlopor/todo#1]
Sin terminar:

https://github.com/adlopor/todo/blob/fedd922d501ee06d91ef6fb7ea1a82a9e8407d0a/src/Controller/TaskController.php#L20-L21

El código sería:
```php
        $user = $this->getUser();
        $task = $repository->findBy([
            'owner' => $user,
        ]);
```

Esta código está mal indentado y sobra un main.

https://github.com/adlopor/todo/blob/fedd922d501ee06d91ef6fb7ea1a82a9e8407d0a/config/packages/security.yaml#L20-L25

Sería

```yaml
        main:
            anonymous: true
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
```
